packages:
  - games/*
  - landing

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  minimist@<0.2.1: '>=0.2.1'
  minimist@<0.2.4: '>=0.2.4'
  node-fetch@<2.6.7: '>=2.6.7'
  tar-fs@>=2.0.0 <2.1.2: '>=2.1.2'
  tar-fs@>=2.0.0 <2.1.3: '>=2.1.3'
  tar-fs@>=2.0.0 <2.1.4: '>=2.1.4'
  ws@>=7.0.0 <7.5.10: '>=7.5.10'
